services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - TZ=UTC
    volumes:
      - pb_data:/app/pb_data
    restart: unless-stopped
    networks:
      - planning-poker

volumes:
  pb_data:
    driver: local

networks:
  planning-poker:
    driver: bridge
