# Local development environment
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8090:8090"
    environment:
      - TZ=UTC
      - DEV_MODE=true
      - CGO_ENABLED=1
      - WS_ALLOWED_ORIGINS=localhost:*,127.0.0.1:*,host.docker.internal:*
    volumes:
      # Mount source code for live reload with Air
      - .:/app
      # Exclude these directories - use container's versions
      - /app/pb_data
      - /app/tmp
      - /app/node_modules
      # Persist database across container restarts
      - pb_data:/app/pb_data
    restart: unless-stopped
    networks:
      - planning-poker

volumes:
  pb_data:
    driver: local

networks:
  planning-poker:
    driver: bridge
