# Local development overrides
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # Mount source code for live reload
      - .:/app
      # Exclude pb_data, tmp, and node_modules from sync (use container's versions)
      - /app/pb_data
      - /app/tmp
      - /app/node_modules
    environment:
      - TZ=UTC
      - CGO_ENABLED=1
    ports:
      - "8090:8090"
